#!/bin/bash

#------------------------------------------------------------------------------
# Script Name: check_network_and_request_dhcp.sh
#
# Description:
#   This script is designed to run on a Proxmox VE (PVE) host with a statically
#   configured IP address. When the host is moved to a new network environment
#   and loses connectivity (e.g., the static IP no longer works), this script
#   attempts to restore connectivity by requesting a temporary IP address via
#   DHCP on the 'vmbr0' interface.
#
#   This script is especially useful when combined with systemd timers and
#   Tailscale for remote access and network recovery.
#
# Maintainer:
#   Charles Shi <schrht@gmail.com>
#
# Generated by:
#   ChatGPT (GPT-4o, Oct 2025)
#
# Tested on:
#   Proxmox VE 8.4.0
#------------------------------------------------------------------------------

LOG_TAG="vmbr0_dhcp_recover"
TARGET_IP="8.8.8.8"
INTERFACE="vmbr0"
DHCP_CLIENT="/sbin/dhclient"

# Check if the network is reachable
if ping -c 2 -W 2 "$TARGET_IP" > /dev/null; then
    logger -t "$LOG_TAG" "Network is OK. No action needed."
    exit 0
fi

logger -t "$LOG_TAG" "Network unreachable. Attempting DHCP recovery on $INTERFACE..."

# Flush all existing IPv4 addresses on the interface
ip addr flush dev "$INTERFACE"

# Release any existing DHCP lease
$DHCP_CLIENT -r "$INTERFACE" > /dev/null 2>&1

# Request a new IP address via DHCP
$DHCP_CLIENT "$INTERFACE"

# Retrieve and log the new IP address
CURRENT_IP=$(ip -4 addr show "$INTERFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n 1)
logger -t "$LOG_TAG" "Current IP address: $CURRENT_IP"

# Test network connectivity again
if ping -c 2 -W 2 "$TARGET_IP" > /dev/null; then
    logger -t "$LOG_TAG" "Network recovery successful."
else
    logger -t "$LOG_TAG" "Network recovery failed."
fi

exit 0
