#!/bin/bash

#------------------------------------------------------------------------------
# Script Name: check_network_and_request_dhcp.sh
#
# Description:
#   This script is designed to run on a Proxmox VE (PVE) host with a statically
#   configured IP address. When the host is moved to a new network environment
#   and loses connectivity (e.g., the static IP no longer works), this script
#   attempts to restore connectivity by requesting a temporary IP address via
#   DHCP on the 'vmbr0' interface.
#
#   This script is especially useful when combined with systemd timers and
#   Tailscale for remote access and network recovery.
#
# Maintainer:
#   Charles Shi <schrht@gmail.com>
#
# Generated by:
#   ChatGPT (GPT-4o, Oct 2025)
#
# Tested on:
#   Proxmox VE 8.4.0
#   Proxmox VE 9.0.3
#------------------------------------------------------------------------------

LOG_TAG="vmbr0_dhcp_recover"
TARGET_IP="8.8.8.8"
INTERFACE="vmbr0"

# Auto-detect dhclient binary
DHCP_CLIENT=$(command -v dhclient || true)

# Function to detect gateway IP address
get_gateway_ip() {
    # Try to get default gateway from routing table
    GATEWAY=$(ip route show default 2>/dev/null | grep -oP 'via \K[\d.]+' | head -n 1)
    
    # If no default route found, try to get gateway from interface route
    if [ -z "$GATEWAY" ]; then
        GATEWAY=$(ip route | grep "dev $INTERFACE" | grep default | grep -oP 'via \K[\d.]+' | head -n 1)
    fi
    
    # If still no gateway, try common gateway addresses based on current IP
    if [ -z "$GATEWAY" ]; then
        CURRENT_IP=$(ip -4 addr show "$INTERFACE" 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n 1)
        if [ -n "$CURRENT_IP" ]; then
            # Extract network prefix (first 3 octets)
            NETWORK_PREFIX=$(echo "$CURRENT_IP" | cut -d. -f1-3)
            # Try common gateway addresses
            for suffix in 1 254; do
                TEST_GATEWAY="${NETWORK_PREFIX}.${suffix}"
                if ping -c 1 -W 1 "$TEST_GATEWAY" > /dev/null 2>&1; then
                    GATEWAY="$TEST_GATEWAY"
                    break
                fi
            done
        fi
    fi
    
    echo "$GATEWAY"
}

# Check if dhclient is available
if [ -z "$DHCP_CLIENT" ] || [ ! -x "$DHCP_CLIENT" ]; then
    logger -t "$LOG_TAG" "Error: dhclient not found. Please install isc-dhcp-client."
    exit 1
fi

# Check if the network is reachable
if ping -c 2 -W 2 "$TARGET_IP" > /dev/null; then
    logger -t "$LOG_TAG" "Network is OK. No action needed."
    exit 0
fi

logger -t "$LOG_TAG" "Network unreachable. Checking gateway connectivity to determine if issue is local or external..."

# Detect gateway IP
GATEWAY_IP=$(get_gateway_ip)

if [ -n "$GATEWAY_IP" ]; then
    logger -t "$LOG_TAG" "Detected gateway: $GATEWAY_IP"
    
    # Check if gateway is reachable
    if ping -c 2 -W 2 "$GATEWAY_IP" > /dev/null; then
        logger -t "$LOG_TAG" "Gateway is reachable but internet is not. This indicates an external network issue (router/internet problem). Skipping DHCP recovery."
        exit 0
    else
        logger -t "$LOG_TAG" "Gateway is unreachable. This indicates a local network configuration issue. Proceeding with DHCP recovery."
    fi
else
    logger -t "$LOG_TAG" "Could not detect gateway. Assuming local network configuration issue. Proceeding with DHCP recovery."
fi

logger -t "$LOG_TAG" "Attempting DHCP recovery on $INTERFACE..."

# Flush all existing IPv4 addresses on the interface
ip addr flush dev "$INTERFACE"

# Release any existing DHCP lease
$DHCP_CLIENT -r "$INTERFACE" > /dev/null 2>&1

# Request a new IP address via DHCP
$DHCP_CLIENT "$INTERFACE"

# Retrieve and log the new IP address
CURRENT_IP=$(ip -4 addr show "$INTERFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n 1)
logger -t "$LOG_TAG" "Current IP address: $CURRENT_IP"

# Test network connectivity again
if ping -c 2 -W 2 "$TARGET_IP" > /dev/null; then
    logger -t "$LOG_TAG" "Network recovery successful."
else
    logger -t "$LOG_TAG" "Network recovery failed."
fi

exit 0

